### PR TITLE
Persist Entities on a Background Thread

### PR DESCRIPTION
**Pull request by frowing**
@groomsy followed your advice from http://toddgrooms.com/2014/04/09/introducing-core-data-mate/ to create a temporary context to save on.

### CODE REVIEW

**Comment by groomsy** [comment]
@frowing See my comment above.

**Comment by frowing** [comment]
@groomsy that's right! thanks

**Comment by frowing** [comment]
@groomsy Can I have your blessing on this one?

**Comment by groomsy** [comment]
@frowing Looks good :+1: :shipit:

**Pull request merged**
